language: java

cache:
  directories:
  - ~/.m2

git:
  depth: 1

branches:
  only:
    - master

install:
  mvn install -Dmaven.test.skip -B -fae -s settings.xml

script:
  mvn test -B -fae -s settings.xml
