/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.mixin.model.transform;

import static org.unidal.agent.mixin.model.Constants.ATTR_ACCESS;
import static org.unidal.agent.mixin.model.Constants.ATTR_CLASS;
import static org.unidal.agent.mixin.model.Constants.ATTR_DESC;
import static org.unidal.agent.mixin.model.Constants.ATTR_INNER_NAME;
import static org.unidal.agent.mixin.model.Constants.ATTR_NAME;
import static org.unidal.agent.mixin.model.Constants.ATTR_OUTER_NAME;
import static org.unidal.agent.mixin.model.Constants.ATTR_SOURCE_CLASS;
import static org.unidal.agent.mixin.model.Constants.ATTR_SOURCE_NAME;
import static org.unidal.agent.mixin.model.Constants.ATTR_SOURCE_OUTER_NAME;
import static org.unidal.agent.mixin.model.Constants.ATTR_SUPER_NAME;
import static org.unidal.agent.mixin.model.Constants.ENTITY_CLASS;
import static org.unidal.agent.mixin.model.Constants.ENTITY_FIELD;
import static org.unidal.agent.mixin.model.Constants.ENTITY_INNER_CLASS;
import static org.unidal.agent.mixin.model.Constants.ENTITY_METHOD;
import static org.unidal.agent.mixin.model.Constants.ENTITY_MIXIN;
import static org.unidal.agent.mixin.model.Constants.ENTITY_SOURCE;
import static org.unidal.agent.mixin.model.Constants.ENTITY_TARGET;

import java.lang.reflect.Array;
import java.util.Collection;

import org.unidal.agent.mixin.model.IEntity;
import org.unidal.agent.mixin.model.IVisitor;
import org.unidal.agent.mixin.model.entity.ClassModel;
import org.unidal.agent.mixin.model.entity.FieldModel;
import org.unidal.agent.mixin.model.entity.InnerClassModel;
import org.unidal.agent.mixin.model.entity.MethodModel;
import org.unidal.agent.mixin.model.entity.MixinModel;
import org.unidal.agent.mixin.model.entity.SourceModel;
import org.unidal.agent.mixin.model.entity.TargetModel;

public class DefaultXmlBuilder implements IVisitor {

   private IVisitor m_visitor = this;

   private int m_level;

   private StringBuilder m_sb;

   private boolean m_compact;

   public DefaultXmlBuilder() {
      this(false);
   }

   public DefaultXmlBuilder(boolean compact) {
      this(compact, new StringBuilder(4096));
   }

   public DefaultXmlBuilder(boolean compact, StringBuilder sb) {
      m_compact = compact;
      m_sb = sb;
      m_sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n");
   }

   public String buildXml(IEntity<?> entity) {
      entity.accept(m_visitor);
      return m_sb.toString();
   }

   protected void endTag(String name) {
      m_level--;

      indent();
      m_sb.append("</").append(name).append(">\r\n");
   }

   protected String escape(Object value) {
      return escape(value, false);
   }
   
   protected String escape(Object value, boolean text) {
      if (value == null) {
         return null;
      }

      String str = toString(value);
      int len = str.length();
      StringBuilder sb = new StringBuilder(len + 16);

      for (int i = 0; i < len; i++) {
         final char ch = str.charAt(i);

         switch (ch) {
         case '<':
            sb.append("&lt;");
            break;
         case '>':
            sb.append("&gt;");
            break;
         case '&':
            sb.append("&amp;");
            break;
         case '"':
            if (!text) {
               sb.append("&quot;");
               break;
            }
         default:
            sb.append(ch);
            break;
         }
      }

      return sb.toString();
   }
   
   protected void indent() {
      if (!m_compact) {
         for (int i = m_level - 1; i >= 0; i--) {
            m_sb.append("   ");
         }
      }
   }

   protected void startTag(String name) {
      startTag(name, false, null);
   }
   
   protected void startTag(String name, boolean closed, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      startTag(name, null, closed, dynamicAttributes, nameValues);
   }

   protected void startTag(String name, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      startTag(name, null, false, dynamicAttributes, nameValues);
   }

   protected void startTag(String name, Object text, boolean closed, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      indent();

      m_sb.append('<').append(name);

      int len = nameValues.length;

      for (int i = 0; i + 1 < len; i += 2) {
         Object attrName = nameValues[i];
         Object attrValue = nameValues[i + 1];

         if (attrValue != null) {
            m_sb.append(' ').append(attrName).append("=\"").append(escape(attrValue)).append('"');
         }
      }

      if (dynamicAttributes != null) {
         for (java.util.Map.Entry<String, String> e : dynamicAttributes.entrySet()) {
            m_sb.append(' ').append(e.getKey()).append("=\"").append(escape(e.getValue())).append('"');
         }
      }

      if (text != null && closed) {
         m_sb.append('>');
         m_sb.append(escape(text, true));
         m_sb.append("</").append(name).append(">\r\n");
      } else {
         if (closed) {
            m_sb.append('/');
         } else {
            m_level++;
         }
   
         m_sb.append(">\r\n");
      }
   }

   @SuppressWarnings("unchecked")
   protected String toString(Object value) {
      if (value instanceof String) {
         return (String) value;
      } else if (value instanceof Collection) {
         Collection<Object> list = (Collection<Object>) value;
         StringBuilder sb = new StringBuilder(32);
         boolean first = true;

         for (Object item : list) {
            if (first) {
               first = false;
            } else {
               sb.append(',');
            }

            if (item != null) {
               sb.append(item);
            }
         }

         return sb.toString();
      } else if (value.getClass().isArray()) {
         int len = Array.getLength(value);
         StringBuilder sb = new StringBuilder(32);
         boolean first = true;

         for (int i = 0; i < len; i++) {
            Object item = Array.get(value, i);

            if (first) {
               first = false;
            } else {
               sb.append(',');
            }

            if (item != null) {
               sb.append(item);
            }
         }
		
         return sb.toString();
      }
 
      return String.valueOf(value);
   }

   @Override
   public void visitClass(ClassModel _class) {
      startTag(ENTITY_CLASS, null, ATTR_CLASS, _class.getClazz());

      if (_class.getTarget() != null) {
         _class.getTarget().accept(m_visitor);
      }

      if (!_class.getSources().isEmpty()) {
         for (SourceModel source : _class.getSources()) {
            source.accept(m_visitor);
         }
      }

      endTag(ENTITY_CLASS);
   }

   @Override
   public void visitField(FieldModel field) {
      startTag(ENTITY_FIELD, true, null, ATTR_ACCESS, field.getAccess(), ATTR_NAME, field.getName(), ATTR_DESC, field.getDesc(), ATTR_SOURCE_NAME, field.getSourceName(), ATTR_SOURCE_CLASS, field.getSourceClass());
   }

   @Override
   public void visitInnerClass(InnerClassModel innerClass) {
      startTag(ENTITY_INNER_CLASS, true, null, ATTR_ACCESS, innerClass.getAccess(), ATTR_NAME, innerClass.getName(), ATTR_OUTER_NAME, innerClass.getOuterName(), ATTR_INNER_NAME, innerClass.getInnerName(), ATTR_SOURCE_NAME, innerClass.getSourceName(), ATTR_SOURCE_OUTER_NAME, innerClass.getSourceOuterName());
   }

   @Override
   public void visitMethod(MethodModel method) {
      startTag(ENTITY_METHOD, true, null, ATTR_ACCESS, method.getAccess(), ATTR_NAME, method.getName(), ATTR_SUPER_NAME, method.getSuperName(), ATTR_SOURCE_NAME, method.getSourceName(), ATTR_SOURCE_CLASS, method.getSourceClass(), ATTR_DESC, method.getDesc());
   }

   @Override
   public void visitMixin(MixinModel mixin) {
      startTag(ENTITY_MIXIN, null);

      if (!mixin.getClasses().isEmpty()) {
         for (ClassModel class_ : mixin.getClasses().values()) {
            class_.accept(m_visitor);
         }
      }

      endTag(ENTITY_MIXIN);
   }

   @Override
   public void visitSource(SourceModel source) {
      startTag(ENTITY_SOURCE, null, ATTR_NAME, source.getName(), ATTR_CLASS, source.getClazz());

      if (!source.getFields().isEmpty()) {
         for (FieldModel field : source.getFields()) {
            field.accept(m_visitor);
         }
      }

      if (!source.getMethods().isEmpty()) {
         for (MethodModel method : source.getMethods()) {
            method.accept(m_visitor);
         }
      }

      if (!source.getInnerClasses().isEmpty()) {
         for (InnerClassModel innerClass : source.getInnerClasses()) {
            innerClass.accept(m_visitor);
         }
      }

      endTag(ENTITY_SOURCE);
   }

   @Override
   public void visitTarget(TargetModel target) {
      startTag(ENTITY_TARGET, null, ATTR_NAME, target.getName());

      if (!target.getFields().isEmpty()) {
         for (FieldModel field : target.getFields()) {
            field.accept(m_visitor);
         }
      }

      if (!target.getMethods().isEmpty()) {
         for (MethodModel method : target.getMethods()) {
            method.accept(m_visitor);
         }
      }

      if (!target.getInnerClasses().isEmpty()) {
         for (InnerClassModel innerClass : target.getInnerClasses()) {
            innerClass.accept(m_visitor);
         }
      }

      endTag(ENTITY_TARGET);
   }
}
