/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.mixin.model.transform;

import org.unidal.agent.mixin.model.entity.ClassModel;
import org.unidal.agent.mixin.model.entity.FieldModel;
import org.unidal.agent.mixin.model.entity.InnerClassModel;
import org.unidal.agent.mixin.model.entity.MethodModel;
import org.unidal.agent.mixin.model.entity.MixinModel;
import org.unidal.agent.mixin.model.entity.SourceModel;
import org.unidal.agent.mixin.model.entity.TargetModel;

public interface IMaker<T> {

   public ClassModel buildClass(T node);

   public FieldModel buildField(T node);

   public InnerClassModel buildInnerClass(T node);

   public MethodModel buildMethod(T node);

   public MixinModel buildMixin(T node);

   public SourceModel buildSource(T node);

   public TargetModel buildTarget(T node);
}
