/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model.transform;

import java.util.ArrayList;
import java.util.List;
import org.unidal.agent.cat.model.entity.ClassModel;
import org.unidal.agent.cat.model.entity.EventModel;
import org.unidal.agent.cat.model.entity.InstrumentModel;
import org.unidal.agent.cat.model.entity.MethodModel;
import org.unidal.agent.cat.model.entity.TransactionModel;

public class DefaultLinker implements ILinker {
   @SuppressWarnings("unused")
   private boolean m_deferrable;

   private List<Runnable> m_deferedJobs = new ArrayList<Runnable>();

   public DefaultLinker(boolean deferrable) {
      m_deferrable = deferrable;
   }

   public void finish() {
      for (Runnable job : m_deferedJobs) {
         job.run();
      }
   }

   @Override
   public boolean onClass(final InstrumentModel parent, final ClassModel _class) {
      parent.addClass(_class);
      return true;
   }

   @Override
   public boolean onEvent(final MethodModel parent, final EventModel event) {
      parent.setEvent(event);
      return true;
   }

   @Override
   public boolean onMethod(final ClassModel parent, final MethodModel method) {
      parent.addMethod(method);
      return true;
   }

   @Override
   public boolean onTransaction(final MethodModel parent, final TransactionModel transaction) {
      parent.setTransaction(transaction);
      return true;
   }
}
