/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model.transform;

import static org.unidal.agent.cat.model.Constants.ATTR_DESC;
import static org.unidal.agent.cat.model.Constants.ATTR_ENABLED;
import static org.unidal.agent.cat.model.Constants.ATTR_NAME;
import static org.unidal.agent.cat.model.Constants.ATTR_TYPE;
import static org.unidal.agent.cat.model.Constants.ELEMENT_KEY;
import static org.unidal.agent.cat.model.Constants.ELEMENT_SUCCESS;
import static org.unidal.agent.cat.model.Constants.ELEMENT_VALUE;
import static org.unidal.agent.cat.model.Constants.ENTITY_CLASS;
import static org.unidal.agent.cat.model.Constants.ENTITY_EVENT;
import static org.unidal.agent.cat.model.Constants.ENTITY_METHOD;
import static org.unidal.agent.cat.model.Constants.ENTITY_ROOT;
import static org.unidal.agent.cat.model.Constants.ENTITY_TRANSACTION;

import java.lang.reflect.Array;
import java.util.Collection;

import org.unidal.agent.cat.model.IEntity;
import org.unidal.agent.cat.model.IVisitor;
import org.unidal.agent.cat.model.entity.ClassModel;
import org.unidal.agent.cat.model.entity.EventModel;
import org.unidal.agent.cat.model.entity.MethodModel;
import org.unidal.agent.cat.model.entity.RootModel;
import org.unidal.agent.cat.model.entity.TransactionModel;

public class DefaultXmlBuilder implements IVisitor {

   private IVisitor m_visitor = this;

   private int m_level;

   private StringBuilder m_sb;

   private boolean m_compact;

   public DefaultXmlBuilder() {
      this(false);
   }

   public DefaultXmlBuilder(boolean compact) {
      this(compact, new StringBuilder(4096));
   }

   public DefaultXmlBuilder(boolean compact, StringBuilder sb) {
      m_compact = compact;
      m_sb = sb;
      m_sb.append("<?xml version=\"1.0\" encoding=\"utf-8\"?>\r\n");
   }

   public String buildXml(IEntity<?> entity) {
      entity.accept(m_visitor);
      return m_sb.toString();
   }

   protected void endTag(String name) {
      m_level--;

      indent();
      m_sb.append("</").append(name).append(">\r\n");
   }

   protected String escape(Object value) {
      return escape(value, false);
   }
   
   protected String escape(Object value, boolean text) {
      if (value == null) {
         return null;
      }

      String str = toString(value);
      int len = str.length();
      StringBuilder sb = new StringBuilder(len + 16);

      for (int i = 0; i < len; i++) {
         final char ch = str.charAt(i);

         switch (ch) {
         case '<':
            sb.append("&lt;");
            break;
         case '>':
            sb.append("&gt;");
            break;
         case '&':
            sb.append("&amp;");
            break;
         case '"':
            if (!text) {
               sb.append("&quot;");
               break;
            }
         default:
            sb.append(ch);
            break;
         }
      }

      return sb.toString();
   }
   
   protected void indent() {
      if (!m_compact) {
         for (int i = m_level - 1; i >= 0; i--) {
            m_sb.append("   ");
         }
      }
   }

   protected void startTag(String name) {
      startTag(name, false, null);
   }
   
   protected void startTag(String name, boolean closed, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      startTag(name, null, closed, dynamicAttributes, nameValues);
   }

   protected void startTag(String name, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      startTag(name, null, false, dynamicAttributes, nameValues);
   }

   protected void startTag(String name, Object text, boolean closed, java.util.Map<String, String> dynamicAttributes, Object... nameValues) {
      indent();

      m_sb.append('<').append(name);

      int len = nameValues.length;

      for (int i = 0; i + 1 < len; i += 2) {
         Object attrName = nameValues[i];
         Object attrValue = nameValues[i + 1];

         if (attrValue != null) {
            m_sb.append(' ').append(attrName).append("=\"").append(escape(attrValue)).append('"');
         }
      }

      if (dynamicAttributes != null) {
         for (java.util.Map.Entry<String, String> e : dynamicAttributes.entrySet()) {
            m_sb.append(' ').append(e.getKey()).append("=\"").append(escape(e.getValue())).append('"');
         }
      }

      if (text != null && closed) {
         m_sb.append('>');
         m_sb.append(escape(text, true));
         m_sb.append("</").append(name).append(">\r\n");
      } else {
         if (closed) {
            m_sb.append('/');
         } else {
            m_level++;
         }
   
         m_sb.append(">\r\n");
      }
   }

   @SuppressWarnings("unchecked")
   protected String toString(Object value) {
      if (value instanceof String) {
         return (String) value;
      } else if (value instanceof Collection) {
         Collection<Object> list = (Collection<Object>) value;
         StringBuilder sb = new StringBuilder(32);
         boolean first = true;

         for (Object item : list) {
            if (first) {
               first = false;
            } else {
               sb.append(',');
            }

            if (item != null) {
               sb.append(item);
            }
         }

         return sb.toString();
      } else if (value.getClass().isArray()) {
         int len = Array.getLength(value);
         StringBuilder sb = new StringBuilder(32);
         boolean first = true;

         for (int i = 0; i < len; i++) {
            Object item = Array.get(value, i);

            if (first) {
               first = false;
            } else {
               sb.append(',');
            }

            if (item != null) {
               sb.append(item);
            }
         }
		
         return sb.toString();
      }
 
      return String.valueOf(value);
   }

   protected void tagWithText(String name, String text, java.util.Map<String, String> attributes) {
      if (text == null) {
         return;
      }
      
      indent();

      m_sb.append('<').append(name);

      if (attributes != null) {
         for (java.util.Map.Entry<String, String> e : attributes.entrySet()) {
            m_sb.append(' ').append(e.getKey()).append("=\"").append(escape(e.getValue())).append('"');
         }
      }

      m_sb.append(">");
      m_sb.append(escape(text, true));
      m_sb.append("</").append(name).append(">\r\n");
   }

   protected void tagWithText(String name, String text, Object... nameValues) {
      if (text == null) {
         return;
      }
      
      indent();

      m_sb.append('<').append(name);

      int len = nameValues.length;

      for (int i = 0; i + 1 < len; i += 2) {
         Object attrName = nameValues[i];
         Object attrValue = nameValues[i + 1];

         if (attrValue != null) {
            m_sb.append(' ').append(attrName).append("=\"").append(escape(attrValue)).append('"');
         }
      }

      m_sb.append(">");
      m_sb.append(escape(text, true));
      m_sb.append("</").append(name).append(">\r\n");
   }

   protected void element(String name, String text, String defaultValue, boolean escape) {
      if (text == null || text.equals(defaultValue)) {
         return;
      }
      
      indent();
      
      m_sb.append('<').append(name).append(">");
      
      if (escape) {
         m_sb.append(escape(text, true));
      } else {
         m_sb.append("<![CDATA[").append(text).append("]]>");
      }
      
      m_sb.append("</").append(name).append(">\r\n");
   }

   @Override
   public void visitClass(ClassModel _class) {
      startTag(ENTITY_CLASS, null, ATTR_NAME, _class.getName(), ATTR_ENABLED, _class.getEnabled());

      if (!_class.getMethods().isEmpty()) {
         for (MethodModel method : _class.getMethods()) {
            method.accept(m_visitor);
         }
      }

      endTag(ENTITY_CLASS);
   }

   @Override
   public void visitEvent(EventModel event) {
      startTag(ENTITY_EVENT, null, ATTR_TYPE, event.getType(), ATTR_NAME, event.getName());

      if (!event.getKeys().isEmpty()) {
         for (String key : event.getKeys()) {
            tagWithText(ELEMENT_KEY, key);
         }
      }

      if (!event.getValues().isEmpty()) {
         for (String value : event.getValues()) {
            tagWithText(ELEMENT_VALUE, value);
         }
      }

      if (!event.getSuccesses().isEmpty()) {
         for (Integer success : event.getSuccesses()) {
            tagWithText(ELEMENT_SUCCESS, success == null ? null : String.valueOf(success));
         }
      }

      endTag(ENTITY_EVENT);
   }

   @Override
   public void visitMethod(MethodModel method) {
      startTag(ENTITY_METHOD, null, ATTR_NAME, method.getName(), ATTR_DESC, method.getDesc());

      if (method.getTransaction() != null) {
         method.getTransaction().accept(m_visitor);
      }

      if (method.getEvent() != null) {
         method.getEvent().accept(m_visitor);
      }

      endTag(ENTITY_METHOD);
   }

   @Override
   public void visitRoot(RootModel root) {
      startTag(ENTITY_ROOT, null);

      if (!root.getClasses().isEmpty()) {
         for (ClassModel class_ : root.getClasses().values()) {
            class_.accept(m_visitor);
         }
      }

      endTag(ENTITY_ROOT);
   }

   @Override
   public void visitTransaction(TransactionModel transaction) {
      startTag(ENTITY_TRANSACTION, null, ATTR_TYPE, transaction.getType(), ATTR_NAME, transaction.getName());

      if (!transaction.getKeys().isEmpty()) {
         for (String key : transaction.getKeys()) {
            tagWithText(ELEMENT_KEY, key);
         }
      }

      if (!transaction.getValues().isEmpty()) {
         for (String value : transaction.getValues()) {
            tagWithText(ELEMENT_VALUE, value);
         }
      }

      if (!transaction.getSuccesses().isEmpty()) {
         for (Integer success : transaction.getSuccesses()) {
            tagWithText(ELEMENT_SUCCESS, success == null ? null : String.valueOf(success));
         }
      }

      endTag(ENTITY_TRANSACTION);
   }
}
