/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model.transform;

import org.unidal.agent.cat.model.entity.ClassModel;
import org.unidal.agent.cat.model.entity.EventModel;
import org.unidal.agent.cat.model.entity.InstrumentModel;
import org.unidal.agent.cat.model.entity.MethodModel;
import org.unidal.agent.cat.model.entity.TransactionModel;

public interface ILinker {

   public boolean onClass(InstrumentModel parent, ClassModel _class);

   public boolean onEvent(MethodModel parent, EventModel event);

   public boolean onMethod(ClassModel parent, MethodModel method);

   public boolean onTransaction(MethodModel parent, TransactionModel transaction);
}
