/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model.transform;

import org.unidal.agent.cat.model.entity.ClassModel;
import org.unidal.agent.cat.model.entity.EventModel;
import org.unidal.agent.cat.model.entity.MethodModel;
import org.unidal.agent.cat.model.entity.RootModel;
import org.unidal.agent.cat.model.entity.TransactionModel;

public interface IMaker<T> {

   public ClassModel buildClass(T node);

   public EventModel buildEvent(T node);

   public String buildKey(T node);

   public MethodModel buildMethod(T node);

   public RootModel buildRoot(T node);

   public Integer buildSuccess(T node);

   public TransactionModel buildTransaction(T node);

   public String buildValue(T node);
}
