/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model.entity;

import static org.unidal.agent.cat.model.Constants.ATTR_NAME;
import static org.unidal.agent.cat.model.Constants.ATTR_DESC;
import static org.unidal.agent.cat.model.Constants.ENTITY_METHOD;

import org.unidal.agent.cat.model.BaseEntity;
import org.unidal.agent.cat.model.IVisitor;

public class MethodModel extends BaseEntity<MethodModel> {
   private String m_name;

   private String m_desc;

   private TransactionModel m_transaction;

   private EventModel m_event;

   public MethodModel() {
   }

   public MethodModel(String name, String desc) {
      m_name = name;
      m_desc = desc;
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitMethod(this);
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof MethodModel) {
         MethodModel _o = (MethodModel) obj;

         if (!equals(getName(), _o.getName())) {
            return false;
         }

         if (!equals(getDesc(), _o.getDesc())) {
            return false;
         }

         return true;
      }

      return false;
   }

   public String getDesc() {
      return m_desc;
   }

   public EventModel getEvent() {
      return m_event;
   }

   public String getName() {
      return m_name;
   }

   public TransactionModel getTransaction() {
      return m_transaction;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_name == null ? 0 : m_name.hashCode());
      hash = hash * 31 + (m_desc == null ? 0 : m_desc.hashCode());

      return hash;
   }

   @Override
   public void mergeAttributes(MethodModel other) {
      assertAttributeEquals(other, ENTITY_METHOD, ATTR_NAME, m_name, other.getName());
      assertAttributeEquals(other, ENTITY_METHOD, ATTR_DESC, m_desc, other.getDesc());

   }

   public MethodModel setDesc(String desc) {
      m_desc = desc;
      return this;
   }

   public MethodModel setEvent(EventModel event) {
      m_event = event;
      return this;
   }

   public MethodModel setName(String name) {
      m_name = name;
      return this;
   }

   public MethodModel setTransaction(TransactionModel transaction) {
      m_transaction = transaction;
      return this;
   }

}
