/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model.entity;

import java.util.LinkedHashMap;
import java.util.Map;

import org.unidal.agent.cat.model.BaseEntity;
import org.unidal.agent.cat.model.IVisitor;

public class RootModel extends BaseEntity<RootModel> {
   private Map<String, ClassModel> m_classes = new LinkedHashMap<String, ClassModel>();

   public RootModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitRoot(this);
   }

   public RootModel addClass(ClassModel _class) {
      m_classes.put(_class.getName(), _class);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof RootModel) {
         RootModel _o = (RootModel) obj;

         if (!equals(getClasses(), _o.getClasses())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public ClassModel findClass(String name) {
      return m_classes.get(name);
   }

   public ClassModel findOrCreateClass(String name) {
      ClassModel class_ = m_classes.get(name);

      if (class_ == null) {
         synchronized (m_classes) {
            class_ = m_classes.get(name);

            if (class_ == null) {
               class_ = new ClassModel(name);
               m_classes.put(name, class_);
            }
         }
      }

      return class_;
   }

   public Map<String, ClassModel> getClasses() {
      return m_classes;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_classes == null ? 0 : m_classes.hashCode());

      return hash;
   }

   @Override
   public void mergeAttributes(RootModel other) {
   }

   public ClassModel removeClass(String name) {
      return m_classes.remove(name);
   }

}
