/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model.entity;

import java.util.ArrayList;
import java.util.List;

import org.unidal.agent.cat.model.BaseEntity;
import org.unidal.agent.cat.model.IVisitor;

public class TransactionModel extends BaseEntity<TransactionModel> {
   private String m_type;

   private String m_name;

   private List<String> m_keies = new ArrayList<String>();

   private List<String> m_values = new ArrayList<String>();

   private List<Integer> m_successes = new ArrayList<Integer>();

   public TransactionModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitTransaction(this);
   }

   public TransactionModel addKey(String key) {
      m_keies.add(key);
      return this;
   }

   public TransactionModel addSuccess(Integer success) {
      m_successes.add(success);
      return this;
   }

   public TransactionModel addValue(String value) {
      m_values.add(value);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof TransactionModel) {
         TransactionModel _o = (TransactionModel) obj;

         if (!equals(getType(), _o.getType())) {
            return false;
         }

         if (!equals(getName(), _o.getName())) {
            return false;
         }

         if (!equals(getKeies(), _o.getKeies())) {
            return false;
         }

         if (!equals(getValues(), _o.getValues())) {
            return false;
         }

         if (!equals(getSuccesses(), _o.getSuccesses())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public List<String> getKeies() {
      return m_keies;
   }

   public String getName() {
      return m_name;
   }

   public List<Integer> getSuccesses() {
      return m_successes;
   }

   public String getType() {
      return m_type;
   }

   public List<String> getValues() {
      return m_values;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_type == null ? 0 : m_type.hashCode());
      hash = hash * 31 + (m_name == null ? 0 : m_name.hashCode());
      for (String e : m_keies) {
         hash = hash * 31 + (e == null ? 0 :e.hashCode());
      }

      for (String e : m_values) {
         hash = hash * 31 + (e == null ? 0 :e.hashCode());
      }

      for (Integer e : m_successes) {
         hash = hash * 31 + (e == null ? 0 :e.hashCode());
      }


      return hash;
   }

   @Override
   public void mergeAttributes(TransactionModel other) {
      if (other.getType() != null) {
         m_type = other.getType();
      }

      if (other.getName() != null) {
         m_name = other.getName();
      }
   }

   public TransactionModel setName(String name) {
      m_name = name;
      return this;
   }

   public TransactionModel setType(String type) {
      m_type = type;
      return this;
   }

}
