/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.mixin.model;

public class Constants {

   public static final String ATTR_ACCESS = "access";

   public static final String ATTR_CLASS = "class";

   public static final String ATTR_DESC = "desc";

   public static final String ATTR_INNER_NAME = "inner-name";

   public static final String ATTR_NAME = "name";

   public static final String ATTR_OUTER_NAME = "outer-name";

   public static final String ATTR_SOURCE_CLASS = "source-class";

   public static final String ATTR_SOURCE_NAME = "source-name";

   public static final String ATTR_SOURCE_OUTER_NAME = "source-outer-name";

   public static final String ATTR_SUPER_NAME = "super-name";

   public static final String ENTITY_CLASS = "class";

   public static final String ENTITY_CLASSES = "classes";

   public static final String ENTITY_FIELD = "field";

   public static final String ENTITY_FIELDS = "fields";

   public static final String ENTITY_INNER_CLASS = "inner-class";

   public static final String ENTITY_INNER_CLASSES = "inner-classes";

   public static final String ENTITY_METHOD = "method";

   public static final String ENTITY_METHODS = "methods";

   public static final String ENTITY_MIXIN = "mixin";

   public static final String ENTITY_SOURCE = "source";

   public static final String ENTITY_SOURCES = "sources";

   public static final String ENTITY_TARGET = "target";
}
