/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.mixin.model;

import org.unidal.agent.mixin.model.entity.ClassModel;
import org.unidal.agent.mixin.model.entity.FieldModel;
import org.unidal.agent.mixin.model.entity.InnerClassModel;
import org.unidal.agent.mixin.model.entity.MethodModel;
import org.unidal.agent.mixin.model.entity.MixinModel;
import org.unidal.agent.mixin.model.entity.SourceModel;
import org.unidal.agent.mixin.model.entity.TargetModel;

public interface IVisitor {

   public void visitClass(ClassModel _class);

   public void visitField(FieldModel field);

   public void visitInnerClass(InnerClassModel innerClass);

   public void visitMethod(MethodModel method);

   public void visitMixin(MixinModel mixin);

   public void visitSource(SourceModel source);

   public void visitTarget(TargetModel target);
}
