/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.mixin.model.entity;

import java.util.LinkedHashMap;
import java.util.Map;

import org.unidal.mixin.model.BaseEntity;
import org.unidal.mixin.model.IVisitor;

public class MixinModel extends BaseEntity<MixinModel> {
   private Map<String, ClassModel> m_classes = new LinkedHashMap<String, ClassModel>();

   public MixinModel() {
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitMixin(this);
   }

   public MixinModel addClass(ClassModel _class) {
      m_classes.put(_class.getClazz(), _class);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof MixinModel) {
         MixinModel _o = (MixinModel) obj;

         if (!equals(getClasses(), _o.getClasses())) {
            return false;
         }


         return true;
      }

      return false;
   }

   public ClassModel findClass(String _class) {
      return m_classes.get(_class);
   }

   public ClassModel findOrCreateClass(String _class) {
      ClassModel class_ = m_classes.get(_class);

      if (class_ == null) {
         synchronized (m_classes) {
            class_ = m_classes.get(_class);

            if (class_ == null) {
               class_ = new ClassModel(_class);
               m_classes.put(_class, class_);
            }
         }
      }

      return class_;
   }

   public Map<String, ClassModel> getClasses() {
      return m_classes;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_classes == null ? 0 : m_classes.hashCode());

      return hash;
   }

   @Override
   public void mergeAttributes(MixinModel other) {
   }

   public ClassModel removeClass(String _class) {
      return m_classes.remove(_class);
   }

}
