/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.mixin.model.entity;

import static org.unidal.mixin.model.Constants.ATTR_NAME;
import static org.unidal.mixin.model.Constants.ENTITY_TARGET;

import java.util.ArrayList;
import java.util.List;

import org.unidal.mixin.model.BaseEntity;
import org.unidal.mixin.model.IVisitor;

public class TargetModel extends BaseEntity<TargetModel> {
   private String m_name;

   private List<FieldModel> m_fields = new ArrayList<FieldModel>();

   private List<MethodModel> m_methods = new ArrayList<MethodModel>();

   private List<InnerClassModel> m_innerClasses = new ArrayList<InnerClassModel>();

   public TargetModel() {
   }

   public TargetModel(String name) {
      m_name = name;
   }

   @Override
   public void accept(IVisitor visitor) {
      visitor.visitTarget(this);
   }

   public TargetModel addField(FieldModel field) {
      m_fields.add(field);
      return this;
   }

   public TargetModel addInnerClass(InnerClassModel innerClass) {
      m_innerClasses.add(innerClass);
      return this;
   }

   public TargetModel addMethod(MethodModel method) {
      m_methods.add(method);
      return this;
   }

   @Override
   public boolean equals(Object obj) {
      if (obj instanceof TargetModel) {
         TargetModel _o = (TargetModel) obj;

         if (!equals(getName(), _o.getName())) {
            return false;
         }

         return true;
      }

      return false;
   }

   public FieldModel findField(String name) {
      for (FieldModel field : m_fields) {
         if (!equals(field.getName(), name)) {
            continue;
         }

         return field;
      }

      return null;
   }

   public InnerClassModel findInnerClass(String name) {
      for (InnerClassModel innerClass : m_innerClasses) {
         if (!equals(innerClass.getName(), name)) {
            continue;
         }

         return innerClass;
      }

      return null;
   }

   public MethodModel findMethod(String name) {
      for (MethodModel method : m_methods) {
         if (!equals(method.getName(), name)) {
            continue;
         }

         return method;
      }

      return null;
   }

   public FieldModel findOrCreateField(String name) {
      synchronized (m_fields) {
         for (FieldModel field : m_fields) {
            if (!equals(field.getName(), name)) {
               continue;
            }

            return field;
         }

         FieldModel field = new FieldModel(name);

         m_fields.add(field);
         return field;
      }
   }

   public InnerClassModel findOrCreateInnerClass(String name) {
      synchronized (m_innerClasses) {
         for (InnerClassModel innerClass : m_innerClasses) {
            if (!equals(innerClass.getName(), name)) {
               continue;
            }

            return innerClass;
         }

         InnerClassModel innerClass = new InnerClassModel(name);

         m_innerClasses.add(innerClass);
         return innerClass;
      }
   }

   public MethodModel findOrCreateMethod(String name) {
      synchronized (m_methods) {
         for (MethodModel method : m_methods) {
            if (!equals(method.getName(), name)) {
               continue;
            }

            return method;
         }

         MethodModel method = new MethodModel(name);

         m_methods.add(method);
         return method;
      }
   }

   public List<FieldModel> getFields() {
      return m_fields;
   }

   public List<InnerClassModel> getInnerClasses() {
      return m_innerClasses;
   }

   public List<MethodModel> getMethods() {
      return m_methods;
   }

   public String getName() {
      return m_name;
   }

   @Override
   public int hashCode() {
      int hash = 0;

      hash = hash * 31 + (m_name == null ? 0 : m_name.hashCode());

      return hash;
   }

   @Override
   public void mergeAttributes(TargetModel other) {
      assertAttributeEquals(other, ENTITY_TARGET, ATTR_NAME, m_name, other.getName());

   }

   public FieldModel removeField(String name) {
      int len = m_fields.size();

      for (int i = 0; i < len; i++) {
         FieldModel field = m_fields.get(i);

         if (!equals(field.getName(), name)) {
            continue;
         }

         return m_fields.remove(i);
      }

      return null;
   }

   public InnerClassModel removeInnerClass(String name) {
      int len = m_innerClasses.size();

      for (int i = 0; i < len; i++) {
         InnerClassModel innerClass = m_innerClasses.get(i);

         if (!equals(innerClass.getName(), name)) {
            continue;
         }

         return m_innerClasses.remove(i);
      }

      return null;
   }

   public MethodModel removeMethod(String name) {
      int len = m_methods.size();

      for (int i = 0; i < len; i++) {
         MethodModel method = m_methods.get(i);

         if (!equals(method.getName(), name)) {
            continue;
         }

         return m_methods.remove(i);
      }

      return null;
   }

   public TargetModel setName(String name) {
      m_name = name;
      return this;
   }

   /********* Code Snippet Start *********/
   public MethodModel findOrCreateMethod(String name, String desc) {
      synchronized (m_methods) {
         for (MethodModel method : m_methods) {
            if (!equals(method.getName(), name)) {
               continue;
            }
            
            if (!equals(method.getDesc(), desc)) {
               continue;
            }
            
            return method;
         }
         
         MethodModel method = new MethodModel(name).setDesc(desc);
         
         m_methods.add(method);
         return method;
      }
   }      

   /********* Code Snippet End *********/
}
