/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.mixin.model.transform;

import static org.unidal.mixin.model.Constants.ENTITY_CLASS;
import static org.unidal.mixin.model.Constants.ENTITY_FIELD;
import static org.unidal.mixin.model.Constants.ENTITY_INNER_CLASS;
import static org.unidal.mixin.model.Constants.ENTITY_METHOD;
import static org.unidal.mixin.model.Constants.ENTITY_MIXIN;
import static org.unidal.mixin.model.Constants.ENTITY_SOURCE;
import static org.unidal.mixin.model.Constants.ENTITY_TARGET;

import java.io.BufferedInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.BufferedReader;
import java.io.Reader;
import java.io.StringReader;
import java.util.Stack;

import javax.xml.parsers.ParserConfigurationException;
import javax.xml.parsers.SAXParserFactory;

import org.xml.sax.Attributes;
import org.xml.sax.InputSource;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

import org.unidal.mixin.model.IEntity;
import org.unidal.mixin.model.entity.ClassModel;
import org.unidal.mixin.model.entity.FieldModel;
import org.unidal.mixin.model.entity.InnerClassModel;
import org.unidal.mixin.model.entity.MethodModel;
import org.unidal.mixin.model.entity.MixinModel;
import org.unidal.mixin.model.entity.SourceModel;
import org.unidal.mixin.model.entity.TargetModel;

public class DefaultSaxParser extends DefaultHandler {

   private DefaultLinker m_linker = new DefaultLinker(true);

   private DefaultSaxMaker m_maker = new DefaultSaxMaker();

   private Stack<String> m_tags = new Stack<String>();

   private Stack<Object> m_objs = new Stack<Object>();

   private IEntity<?> m_entity;

   private StringBuilder m_text = new StringBuilder();

   public static MixinModel parse(InputStream in) throws SAXException, IOException {
      return parseEntity(MixinModel.class, in);
   }

   public static MixinModel parse(Reader reader) throws SAXException, IOException {
      return parseEntity(MixinModel.class, reader);
   }

   public static MixinModel parse(String xml) throws SAXException, IOException {
      return parseEntity(MixinModel.class, xml);
   }

   @SuppressWarnings("unchecked")
   private static <T extends IEntity<?>> T parseEntity(Class<T> type, InputSource is) throws SAXException, IOException {
      try {
         DefaultSaxParser parser = new DefaultSaxParser();
         SAXParserFactory factory = SAXParserFactory.newInstance();

         factory.setValidating(false);
         factory.setFeature("http://xml.org/sax/features/validation", false);

         factory.newSAXParser().parse(is, parser);
         parser.m_linker.finish();
         return (T) parser.getEntity();
      } catch (ParserConfigurationException e) {
         throw new IllegalStateException("Unable to get SAX parser instance!", e);
      }
   }

   public static <T extends IEntity<?>> T parseEntity(Class<T> type, InputStream in) throws SAXException, IOException {
      return parseEntity(type, new InputSource(removeBOM(in)));
   }

   public static <T extends IEntity<?>> T parseEntity(Class<T> type, Reader reader) throws SAXException, IOException {
      return parseEntity(type, new InputSource(removeBOM(reader)));
   }

   public static <T extends IEntity<?>> T parseEntity(Class<T> type, String xml) throws SAXException, IOException {
      return parseEntity(type, new InputSource(new StringReader(removeBOM(xml))));
   }

   // to remove Byte Order Mark(BOM) at the head of windows utf-8 file
   @SuppressWarnings("unchecked")
   private static <T> T removeBOM(T obj) throws IOException {
      if (obj instanceof String) {
         String str = (String) obj;

         if (str.length() != 0 && str.charAt(0) == 0xFEFF) {
            return (T) str.substring(1);
         } else {
            return obj;
         }
      } else if (obj instanceof InputStream) {
         BufferedInputStream in = new BufferedInputStream((InputStream) obj);

         in.mark(3);

         if (in.read() != 0xEF || in.read() != 0xBB || in.read() != 0xBF) {
            in.reset();
         }

         return (T) in;
      } else if (obj instanceof Reader) {
         BufferedReader in = new BufferedReader((Reader) obj);

         in.mark(1);

         if (in.read() != 0xFEFF) {
            in.reset();
         }

         return (T) in;
      } else {
         return obj;
      }
   }

   @SuppressWarnings("unchecked")
   protected <T> T convert(Class<T> type, String value, T defaultValue) {
      if (value == null || value.length() == 0) {
         return defaultValue;
      }

      if (type == Boolean.class) {
         return (T) Boolean.valueOf(value);
      } else if (type == Integer.class) {
         return (T) Integer.valueOf(value);
      } else if (type == Long.class) {
         return (T) Long.valueOf(value);
      } else if (type == Short.class) {
         return (T) Short.valueOf(value);
      } else if (type == Float.class) {
         return (T) Float.valueOf(value);
      } else if (type == Double.class) {
         return (T) Double.valueOf(value);
      } else if (type == Byte.class) {
         return (T) Byte.valueOf(value);
      } else if (type == Character.class) {
         return (T) (Character) value.charAt(0);
      } else {
         return (T) value;
      }
   }

   @Override
   public void characters(char[] ch, int start, int length) throws SAXException {
      m_text.append(ch, start, length);
   }

   @Override
   public void endElement(String uri, String localName, String qName) throws SAXException {
      if (uri == null || uri.length() == 0) {
         m_objs.pop();
         m_tags.pop();

      }

      m_text.setLength(0);
   }

   private IEntity<?> getEntity() {
      return m_entity;
   }

   protected String getText() {
      return m_text.toString();
   }

   private void parseForClass(ClassModel parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ENTITY_TARGET.equals(qName)) {
         TargetModel target = m_maker.buildTarget(attributes);

         m_linker.onTarget(parentObj, target);
         m_objs.push(target);
      } else if (ENTITY_SOURCE.equals(qName)) {
         SourceModel source = m_maker.buildSource(attributes);

         m_linker.onSource(parentObj, source);
         m_objs.push(source);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under class!", qName));
      }

      m_tags.push(qName);
   }

   private void parseForField(FieldModel parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      m_objs.push(parentObj);
      m_tags.push(qName);
   }

   private void parseForInnerClass(InnerClassModel parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      m_objs.push(parentObj);
      m_tags.push(qName);
   }

   private void parseForMethod(MethodModel parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      m_objs.push(parentObj);
      m_tags.push(qName);
   }

   private void parseForMixin(MixinModel parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ENTITY_CLASS.equals(qName)) {
         ClassModel class_ = m_maker.buildClass(attributes);

         m_linker.onClass(parentObj, class_);
         m_objs.push(class_);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under mixin!", qName));
      }

      m_tags.push(qName);
   }

   private void parseForSource(SourceModel parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ENTITY_FIELD.equals(qName)) {
         FieldModel field = m_maker.buildField(attributes);

         m_linker.onField(parentObj, field);
         m_objs.push(field);
      } else if (ENTITY_METHOD.equals(qName)) {
         MethodModel method = m_maker.buildMethod(attributes);

         m_linker.onMethod(parentObj, method);
         m_objs.push(method);
      } else if (ENTITY_INNER_CLASS.equals(qName)) {
         InnerClassModel innerClass = m_maker.buildInnerClass(attributes);

         m_linker.onInnerClass(parentObj, innerClass);
         m_objs.push(innerClass);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under source!", qName));
      }

      m_tags.push(qName);
   }

   private void parseForTarget(TargetModel parentObj, String parentTag, String qName, Attributes attributes) throws SAXException {
      if (ENTITY_FIELD.equals(qName)) {
         FieldModel field = m_maker.buildField(attributes);

         m_linker.onField(parentObj, field);
         m_objs.push(field);
      } else if (ENTITY_METHOD.equals(qName)) {
         MethodModel method = m_maker.buildMethod(attributes);

         m_linker.onMethod(parentObj, method);
         m_objs.push(method);
      } else if (ENTITY_INNER_CLASS.equals(qName)) {
         InnerClassModel innerClass = m_maker.buildInnerClass(attributes);

         m_linker.onInnerClass(parentObj, innerClass);
         m_objs.push(innerClass);
      } else {
         throw new SAXException(String.format("Element(%s) is not expected under target!", qName));
      }

      m_tags.push(qName);
   }

   private void parseRoot(String qName, Attributes attributes) throws SAXException {
      if (ENTITY_MIXIN.equals(qName)) {
         MixinModel mixin = m_maker.buildMixin(attributes);

         m_entity = mixin;
         m_objs.push(mixin);
         m_tags.push(qName);
      } else if (ENTITY_CLASS.equals(qName)) {
         ClassModel _class = m_maker.buildClass(attributes);

         m_entity = _class;
         m_objs.push(_class);
         m_tags.push(qName);
      } else if (ENTITY_TARGET.equals(qName)) {
         TargetModel target = m_maker.buildTarget(attributes);

         m_entity = target;
         m_objs.push(target);
         m_tags.push(qName);
      } else if (ENTITY_FIELD.equals(qName)) {
         FieldModel field = m_maker.buildField(attributes);

         m_entity = field;
         m_objs.push(field);
         m_tags.push(qName);
      } else if (ENTITY_METHOD.equals(qName)) {
         MethodModel method = m_maker.buildMethod(attributes);

         m_entity = method;
         m_objs.push(method);
         m_tags.push(qName);
      } else if (ENTITY_INNER_CLASS.equals(qName)) {
         InnerClassModel innerClass = m_maker.buildInnerClass(attributes);

         m_entity = innerClass;
         m_objs.push(innerClass);
         m_tags.push(qName);
      } else if (ENTITY_SOURCE.equals(qName)) {
         SourceModel source = m_maker.buildSource(attributes);

         m_entity = source;
         m_objs.push(source);
         m_tags.push(qName);
      } else {
         throw new SAXException("Unknown root element(" + qName + ") found!");
      }
   }

   @Override
   public void startElement(String uri, String localName, String qName, Attributes attributes) throws SAXException {
      if (uri == null || uri.length() == 0) {
         if (m_objs.isEmpty()) { // root
            parseRoot(qName, attributes);
         } else {
            Object parent = m_objs.peek();
            String tag = m_tags.peek();

            if (parent instanceof MixinModel) {
               parseForMixin((MixinModel) parent, tag, qName, attributes);
            } else if (parent instanceof ClassModel) {
               parseForClass((ClassModel) parent, tag, qName, attributes);
            } else if (parent instanceof TargetModel) {
               parseForTarget((TargetModel) parent, tag, qName, attributes);
            } else if (parent instanceof FieldModel) {
               parseForField((FieldModel) parent, tag, qName, attributes);
            } else if (parent instanceof MethodModel) {
               parseForMethod((MethodModel) parent, tag, qName, attributes);
            } else if (parent instanceof InnerClassModel) {
               parseForInnerClass((InnerClassModel) parent, tag, qName, attributes);
            } else if (parent instanceof SourceModel) {
               parseForSource((SourceModel) parent, tag, qName, attributes);
            } else {
               throw new RuntimeException(String.format("Unknown entity(%s) under %s!", qName, parent.getClass().getName()));
            }
         }

         m_text.setLength(0);
        } else {
         throw new SAXException(String.format("Namespace(%s) is not supported by %s.", uri, this.getClass().getName()));
      }
   }
}
