/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.mixin.model.transform;

import org.unidal.mixin.model.entity.ClassModel;
import org.unidal.mixin.model.entity.FieldModel;
import org.unidal.mixin.model.entity.InnerClassModel;
import org.unidal.mixin.model.entity.MethodModel;
import org.unidal.mixin.model.entity.MixinModel;
import org.unidal.mixin.model.entity.SourceModel;
import org.unidal.mixin.model.entity.TargetModel;

public interface ILinker {

   public boolean onClass(MixinModel parent, ClassModel _class);

   public boolean onField(TargetModel parent, FieldModel field);

   public boolean onField(SourceModel parent, FieldModel field);

   public boolean onInnerClass(TargetModel parent, InnerClassModel innerClass);

   public boolean onInnerClass(SourceModel parent, InnerClassModel innerClass);

   public boolean onMethod(TargetModel parent, MethodModel method);

   public boolean onMethod(SourceModel parent, MethodModel method);

   public boolean onSource(ClassModel parent, SourceModel source);

   public boolean onTarget(ClassModel parent, TargetModel target);
}
