/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model;

public class Constants {

   public static final String ATTR_DESC = "desc";

   public static final String ATTR_ENABLED = "enabled";

   public static final String ATTR_NAME = "name";

   public static final String ATTR_TYPE = "type";

   public static final String ELEMENT_KEY = "key";

   public static final String ELEMENT_KEIES = "keies";

   public static final String ELEMENT_SUCCESS = "success";

   public static final String ELEMENT_SUCCESSES = "successes";

   public static final String ELEMENT_VALUE = "value";

   public static final String ELEMENT_VALUES = "values";

   public static final String ENTITY_CLASS = "class";

   public static final String ENTITY_CLASSES = "classes";

   public static final String ENTITY_EVENT = "event";

   public static final String ENTITY_METHOD = "method";

   public static final String ENTITY_METHODS = "methods";

   public static final String ENTITY_ROOT = "root";

   public static final String ENTITY_TRANSACTION = "transaction";
}
