/* THIS FILE WAS AUTO GENERATED BY codegen-maven-plugin, DO NOT EDIT IT */
package org.unidal.agent.cat.model;

import org.unidal.agent.cat.model.entity.ClassModel;
import org.unidal.agent.cat.model.entity.EventModel;
import org.unidal.agent.cat.model.entity.InstrumentModel;
import org.unidal.agent.cat.model.entity.MethodModel;
import org.unidal.agent.cat.model.entity.TransactionModel;

public interface IVisitor {

   public void visitClass(ClassModel _class);

   public void visitEvent(EventModel event);

   public void visitInstrument(InstrumentModel instrument);

   public void visitMethod(MethodModel method);

   public void visitTransaction(TransactionModel transaction);
}
